### ISSUE TITLE
Add 2 new memes

### ISSUE THREAD

**Issue by Petrosdevri** [Alexandra-Haynes/hacktoberfest2023-memes-collection#12]
## Title: Add 2 new memes
_[Report/Suggestion]: Briefly describe the issue here_

---

### Type:
- [ ] Inappropriate Content Report
- [X] Enhancement Suggestion

---

### Description:
I would like to add 2 memes to the page.

---

### Location:
_If reporting inappropriate content, please provide a link or the path to the file or location in the repository where the content can be found._

---

### Additional Context:
_Add any other context or screenshots about the report/suggestion here. For instance, if you're suggesting a feature, explain why you believe it would benefit the project._

---

### Guidelines:

**For Inappropriate Content**: 
We strive to maintain a positive and inclusive environment. If something is reported as inappropriate, it will be evaluated, and actions will be taken accordingly. When reporting, please be clear and constructive.

**For Enhancement Suggestions**: 
All suggestions are welcome! If you have ideas on how to improve the project or its functionality, we'd love to hear them.

**Comment by Alexandra-Haynes** [comment]
Hi, Petros! Thank you for being here. Please go ahead and create a PR with your favorite memes 😃  I will close this issue here and we look forward to review your PR. Please check README.md for instructions, if needed
