### ISSUE TITLE
Update babel dependency 

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#15]
## Title

The dev dependency for babel seems to be causing a problem when installing the node modules

### Type
- [X] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Location

/package.json

### Additional Context

<img width="1061" alt="Screenshot 2023-10-03 at 12 07 59 AM" src="https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/44416323/1fda7a87-e02b-4e75-b264-8f467e69dabc">

After some research I saw this is a common bug with npm. One potential solution which worked for me was updating the babel dependency to version  "^7.21.11". This is the latest version of the package.

https://www.npmjs.com/package/@babel/plugin-proposal-private-property-in-object

**Comment by Vishal-1004** [comment]
Thanks for bringing this to me, I will surely update this.

**Comment by Komal914** [comment]
Closing this post merge of #19
