### ISSUE TITLE
Create components folder

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#16]
## Title

Code organization

### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Description

There is no components folder. We should add that and move files like Jokes.js, and Memes.js to organize code. That way future components like header/footer have a place to go.

### Location

/src

### Additional Context

<img width="200" alt="Screenshot 2023-10-03 at 12 29 40 AM" src="https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/44416323/6876c97b-5dcf-4e7b-b189-0b8b44ebf5a2">

**Comment by Vishal-1004** [comment]
That's really a very nice idea.

**Comment by Komal914** [comment]
Closing this post merge #19
