### ISSUE TITLE
Layout: Generate Button

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#18]
## Title

The generate button under the meme needs some padding or margin to keep consistent layout with the generate button under jokes

### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Location

src/GlobalStyle.js

### Additional Context

<img width="285" alt="Screenshot 2023-10-03 at 3 00 39 PM" src="https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/44416323/b0934894-f4f4-4eb4-81d3-8d89b8ef7bce">

**Comment by Alexandra-Haynes** [comment]
Komal, thank you for being here and pointing this out. You are right, the layout can use some improvements. Go ahead and make a PR with your idea and we'll keep the conversation going there 😄
