### ISSUE TITLE
Create a header component 

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#19]
## Title

1. Create a header component in src/components
2. Import inside App.js
3. Render it above Memes

### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Description

The header should have a title of the project, and a link to the Github repository

**Comment by pedaars** [comment]
I would like to pick up this issue, please. 
Did you have any rough design in mind?

**Comment by Komal914** [comment]
Hey @pedaars, I am just a contributor. @Alexandra-Haynes is probably the best person for this.

**Comment by Alexandra-Haynes** [comment]
Thank you, @Komal914 & @pedaars! Please go ahead and make a PR with your header idea, just keep in mind that, unfortunately, this project was excluded from hacktoberfest because it does not 'have a lasting effect on people and technology long after October'. I am sorry for any inconvenience...

**Comment by Komal914** [comment]
I still enjoyed working on the project :) no worries! @Alexandra-Haynes
