### ISSUE TITLE
Explore new layouts and website colors 

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#20]
## Title

Check out other websites and brainstorm some ideas for colors/ layouts

### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Description

Helpful Links: 
- https://palettes.shecodes.io/
- https://www.canva.com/colors/color-palette-generator/
- https://www.wix.com/blog/website-layouts

### Additional Context

Personally I liked this layout for memes/jokes
<img width="803" alt="Screenshot 2023-10-03 at 3 14 36 PM" src="https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/44416323/42c0eafc-69a2-469a-ad48-acbb773920b0">

**Comment by Alexandra-Haynes** [comment]
Hi! Please create a PR with your design idea and we'll go from there! 🚀
