### ISSUE TITLE
Getting error during npm package installing 

### ISSUE THREAD

**Issue by harshal255** [Alexandra-Haynes/hacktoberfest2023-memes-collection#29]
## I am getting this error during installing npm packages.

![image](https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/93152436/f4c26135-8d72-4eda-aa82-46ceecdb8b0a)
![image](https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/93152436/57fef8c1-bbab-4a43-a473-93f2ed640616)

### how can I solve this error??

**Comment by pedaars** [comment]
change the package to this @babel/plugin-transform-private-property-in-object.
Heads up this repo has been blacklisted from hacktoberfest so pr's will not count

**Comment by harshal255** [comment]
okay😐
