### ISSUE TITLE
Random Joke and Meme Generator 

### ISSUE THREAD

**Issue by Vishal-1004** [Alexandra-Haynes/hacktoberfest2023-memes-collection#3]
## Title:
Random Joke and Meme Generator

### Description:
You idea of displaying all the memes and joke is nice but if the number of memes and joke keep on increasing then the website will grow to big vertically. So to avoid this we can make this website as a random Joke or Memes generator were anyone can click on a button to get a new joke or a new meme as they like and thus the vertical length will also be reduced.

---

### Location:
I would like to make these changes in "src" folder of this repository were i might edit the existing js file or even create new more files as per the need.
---

**For Enhancement Suggestions**: 
I am quite experienced person with good front end knowledge so i would also like to work on some UX part of the website if you agree.
But for  now i wish if we could make this website of your as random joke and memes generator.
Where beginners can continue with giving their memes and jokes as usually and developers like me can update the appearance and feature of the website.

@Alexandra-Haynes

**Comment by Alexandra-Haynes** [comment]
Vishal, I think your idea is awesome and I would like to collaborate with you on this project! 🔥

**Comment by Vishal-1004** [comment]
I appreciate it mam,
So before we start further on it, can you tell me what kind of design do you expect for this website.
Since we are building the website on a very basic idea so should we just keep two sections (one for memes and one for jokes) were one - one meme and joke is displayed at a time in card like design which even has a button to render new memes or jokes .
This would be the maximum design possible I guess.

**Comment by Alexandra-Haynes** [comment]
Honestly, I am curious what's your design idea, so it would be awesome if you could play with it, make it look good to you, submit a PR and we go from there. As you can see, right now it's just a simple render, no style. So feel free to have fun with it and we'll work on it together! I'm super excited to see where this goes! 😃

**Comment by Vishal-1004** [comment]
Roger mam

**Comment by Vishal-1004** [comment]
https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/94651481/a73b2379-8b16-4739-8f9d-577c420cd5e1

@Alexandra-Haynes

**Comment by Alexandra-Haynes** [comment]
@Vishal-1004, your contributions and ideas are truly impressive! 🔥  I'm genuinely appreciative of the effort you're putting into this discussion. The video explanation you provided is a fantastic touch and really helps to illustrate your idea clearly. I'm excited to move forward with this conversation, and once we have all the details ironed out, I'll test the implementation on my end to ensure it integrates smoothly.

I'm also thrilled that you mentioned how this project can serve as an opportunity to encourage other developers to make their first open source contributions. 🚀  That aligns perfectly with the goal I had in mind for this project – to make it approachable and enjoyable for newcomers.

Let's brainstorm some small, beginner-friendly issues with ideas for easy, incremental improvements. We can also prioritize updating the documentation to reflect the new changes, making it easy for first-time contributors to work on this project. That way, we'll ensure that our project is not only accessible but also well-documented for everyone interested in contributing.

Additionally, considering that Hacktoberfest begins on October 1st and counts open-source contributions starting from that date, I suggest that we aim to make this pull request on that day. This will allow your contributions to be counted towards your Hacktoberfest goals.

That being said, please create this PR on October 1st, we'll test it and merge it, then we'll create a series of small issues for offer other the opportunity to collaborate with us as part of the Hacktoberfest. I plan on making a LinkedIn post to share this project and encourage people to join us on that day (I will tag you, if that's ok for you).

Well, this is awesome! I'm excited to see how this project evolves! Thank you again, Vishal!

**Comment by Vishal-1004** [comment]
@Alexandra-Haynes, first of all thanks a lot mam for giving your time and considering my work. 

Moving forward with this repository i have certain suggestions (listed below):

- In our Readme.md file we must clearly mention how a "Beginner" and a "Skilled" person can contribute to this repository.
-  Beginner should be guided to make their first pull request by giving either memes or jokes, for this we must write a step by step procedure in the Readme.md file which they are suppose to follow. Doing so they will feel confident and will gain experience on working with git and GitHub commands.
- Skilled persons can create "Issues" like i did and can work even on developing the website or the code which we have written.
- Since we are not doing something way out of our field so even an averagely skilled person like me can work on the development of the website.
- In this way we will be able to provide this repository for both the groups of people. Thus a good number of contributes should be willing to contribute to this repository.

Now coming to the suggestions regarding the code which i have been writing:

- I have noticed that you can created a folder in "src" named "Jokes" which contains all the jokes in form of Js files which can be difficult for developers to work and more over it can be space consuming.
- To overcome all this i think we must use a single JSON file which will have all the jokes as well as their author 's name, Why i am suggesting for this is because JSON is a light weight file and working on it very easy when it comes to generating random data. More over the people who want to contribute jokes can directly add their jokes in this JSON file.
- Like wise we can think of doing the same for Memes too.

This is all what i have to say, i will try doing coding part as i have talked above. Once i am done from my side i will make a PR on 1st of October so that you can verify the code and merge the PR to the main branch if everything is fine.
Then you can work on updating the Readme.md file as per your wish and finally we can proceed with our future plans.

I will send you a connection request on LinkedIn shortly.

**Comment by Alexandra-Haynes** [comment]
that sounds great! Make sure to register for hacktoberfest on https://hacktoberfest.com/ and we'll start implementing our ideas on October 1st 🎉

**Comment by Vishal-1004** [comment]
https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/94651481/e7183cc2-1891-46ce-a671-389d07c72c8c

**Comment by Alexandra-Haynes** [comment]
@Vishal-1004 thank you for recording yourself again to show your code. This all looks great! I can't wait to merge it on October 1st and share it out there with the world 🛩️

**Comment by Vishal-1004** [comment]
sure mam

**Comment by Vishal-1004** [comment]
https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/94651481/f5ef86dd-fae4-4809-a801-8012565d64a6

**Comment by Alexandra-Haynes** [comment]
Oh, that is a good point! I think we get the same joke in a row just because we have just 3-4 jokes as of now. As people commit more jokes and memes, the chance of getting the same joke/meme in a row will gradually decrease, but yes this is a  great UX improvement! 🔥
