### ISSUE TITLE
Header is not Visible on the hosted website

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#33]
### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Description

Post merge #19, the header is not visible on the live page. 

### Location

/src/components/header

### Additional Context

Not sure if we need to re-deploy or we are not rendering it correctly

**Comment by Alexandra-Haynes** [comment]
Please try again now. For the new changes to be reflected on the live link, I have to redeploy the project.
