### ISSUE TITLE
Update Read me file

### ISSUE THREAD

**Issue by Komal914** [Alexandra-Haynes/hacktoberfest2023-memes-collection#34]
## Title

Since the project has been excluded from the hackathon, we should get rid of the hackfest info.

### Type
- [x] Enhancement Suggestion
- [ ] Inappropriate Content Report

### Description

Remove all hacktober fest details

### Location

readme file

**Comment by Alexandra-Haynes** [comment]
You are right, I updated the readme. thank you!
