### ISSUE TITLE
Fix the README.md file documentation

### ISSUE THREAD

**Issue by hparashar27** [Alexandra-Haynes/hacktoberfest2023-memes-collection#5]
## Title:
Actually everything is fine in the readme.md file only one thing is not correct there - 

![er](https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/96375055/7668bfe4-ed7f-456c-ac75-55650c6dc55a)

"Earn a T-Shirt: Complete the challenge and earn a limited edition T-shirt." because it is mentioned in the FAQ  section of hacktoberfest site that this year there is no t-shirt reward. 

link - https://hacktoberfest.com/participation/#faq
![sol](https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection/assets/96375055/d3d0ce6d-eac9-4152-9bb6-2819364800b3)

So, by removing or correcting that point from the readme.Md file , this issue can be solved 

---

### Description:
_Please provide a detailed description. If you're reporting inappropriate content, specify which meme/joke and why you find it inappropriate. If suggesting an enhancement, describe what you'd like to see improved or added._

---

### Location:

2nd point - https://github.com/Alexandra-Haynes/hacktoberfest2023-memes-collection#why-contribute 

---

### Additional Context:
_Add any other context or screenshots about the report/suggestion here. For instance, if you're suggesting a feature, explain why you believe it would benefit the project._

---

### Guidelines:

**For Inappropriate Content**: 
We strive to maintain a positive and inclusive environment. If something is reported as inappropriate, it will be evaluated, and actions will be taken accordingly. When reporting, please be clear and constructive.

**For Enhancement Suggestions**: 
All suggestions are welcome! If you have ideas on how to improve the project or its functionality, we'd love to hear them.

**Comment by hparashar27** [comment]
@Alexandra-Haynes can i fix this ?

**Comment by Alexandra-Haynes** [comment]
Harsh, thank you for wanting to contribute to this project. I just made a PR fixing this issue in the readme.md file. You are correct, this year Hacktoberfest does not offer t-shirts anymore. Thank you for creating this issue and pointing this out! Please feel free to make a PR and add your favorite coding meme/joke 🔥

**Comment by Alexandra-Haynes** [comment]
I will close this issue now, as the problem was fixed.
